window.commandUnits = [
  { unit: "Chapter 1: Getting Started with the Basics", items: [
    { command: "pwd", summary: "Print the current working directory.", syntax: "pwd", purpose: "Shows the absolute path of the directory the shell is currently using.", usages: ["Confirm your location before copying or deleting files.", "Use it while navigating nested Linux directories."], flags: ["-P: show the physical path without symlinks.", "-L: show the logical path when supported."], examples: [{ title: "Show current directory", code: "pwd", explanation: "Prints the full path of the active working directory." }, { title: "Resolve symbolic links", code: "pwd -P", explanation: "Shows the physical path rather than a symlinked path." }] },
    { command: "whoami", summary: "Display the current effective username.", syntax: "whoami", purpose: "Tells you which user account is running the current shell session.", usages: ["Verify whether you are operating as root or a standard user.", "Useful before running administrative commands."], flags: ["Most basic usage does not need flags."], examples: [{ title: "Check current user", code: "whoami", explanation: "Prints the effective username for the current shell." }] },
    { command: "cd", summary: "Change the current working directory.", syntax: "cd [directory]", purpose: "Moves the shell session into another directory.", usages: ["Navigate into project, system, or home directories.", "Use special path shortcuts like .., ~, and -."], flags: ["..: move to the parent directory.", "~: jump to the home directory.", "-: return to the previous directory."], examples: [{ title: "Open a system directory", code: "cd /etc", explanation: "Changes the working directory to /etc." }, { title: "Return to the last directory", code: "cd -", explanation: "Switches back to the previously used directory." }] },
    { command: "ls", summary: "List files and directories.", syntax: "ls [options] [path]", purpose: "Displays directory contents and can show metadata such as permissions, size, and timestamps.", usages: ["Inspect the current directory.", "Use long output for ownership and permission checks."], flags: ["-l: long listing format.", "-a: include hidden files.", "-h: human-readable sizes.", "-R: recursive listing."], examples: [{ title: "Detailed listing", code: "ls -lah", explanation: "Shows hidden files, permissions, owners, sizes, and timestamps." }, { title: "List another path", code: "ls -l /var/log", explanation: "Displays the content of /var/log in long format." }] },
    { command: "man", summary: "Open manual pages for commands.", syntax: "man <command>", purpose: "Shows built-in documentation for Linux commands and system interfaces.", usages: ["Learn syntax and flags for a command.", "Search command documentation locally on a Linux system."], flags: ["-k <term>: search manual page names and descriptions.", "q: quit the pager once you finish reading."], examples: [{ title: "Read the manual for ls", code: "man ls", explanation: "Opens the manual page for ls." }, { title: "Search manual topics", code: "man -k network", explanation: "Searches manual page names for network-related topics." }] },
    { command: "locate", summary: "Search for files using a prebuilt database.", syntax: "locate <pattern>", purpose: "Finds files quickly by name using an indexed file database.", usages: ["Search for configuration files or tool paths fast.", "Useful when find would be too slow on a large filesystem."], flags: ["-i: case-insensitive search.", "-c: count matches instead of printing all results."], examples: [{ title: "Locate a wordlist", code: "locate rockyou", explanation: "Searches the system database for names containing rockyou." }, { title: "Count matches", code: "locate -c passwd", explanation: "Reports how many indexed paths match passwd." }] },
    { command: "whereis", summary: "Locate binaries, source files, and manual pages.", syntax: "whereis <command>", purpose: "Shows the binary location, source path, and man page path for a program when available.", usages: ["Find where a command binary lives.", "Check whether a tool has a manual page installed."], flags: ["-b: search only for binaries.", "-m: search only for manual pages."], examples: [{ title: "Find program paths", code: "whereis nmap", explanation: "Shows the known binary and manual page locations for nmap." }, { title: "Search for binary only", code: "whereis -b bash", explanation: "Looks only for the bash executable location." }] },
    { command: "which", summary: "Find a command in the PATH.", syntax: "which <command>", purpose: "Tells you which executable the shell will run when you type a command name.", usages: ["Check whether a program is installed and in PATH.", "Resolve which version of a command will execute first."], flags: ["-a: show all matching paths in PATH."], examples: [{ title: "Resolve a command path", code: "which python3", explanation: "Shows the executable path for python3." }, { title: "Show every match", code: "which -a bash", explanation: "Prints all bash binaries found in the PATH." }] },
    { command: "find", summary: "Search a directory tree by conditions.", syntax: "find <path> [tests] [actions]", purpose: "Recursively searches files and directories using rules such as name, type, size, or time.", usages: ["Locate files by name or extension.", "Filter by file type or age."], flags: ["-name <pattern>: match by name.", "-type f|d: limit to files or directories.", "-mtime <n>: filter by modification age."], examples: [{ title: "Find shell scripts", code: "find . -type f -name \"*.sh\"", explanation: "Searches the current directory tree for shell script files." }, { title: "Find old logs", code: "find /var/log -type f -mtime +7", explanation: "Lists log files modified more than seven days ago." }] },
    { command: "touch", summary: "Create empty files or update timestamps.", syntax: "touch [options] <file>", purpose: "Creates a new empty file if needed or updates timestamp metadata on an existing file.", usages: ["Create placeholder files quickly.", "Update timestamps during testing."], flags: ["-a: modify access time only.", "-m: modify modification time only.", "-c: do not create a file if it does not exist."], examples: [{ title: "Create a file", code: "touch notes.txt", explanation: "Creates notes.txt if it is missing." }, { title: "Update only modification time", code: "touch -m report.txt", explanation: "Changes the modification time without altering access time." }] },
    { command: "mkdir", summary: "Create directories.", syntax: "mkdir [options] <directory>", purpose: "Builds one or more new directories.", usages: ["Create working folders for projects or labs.", "Create nested paths in one step."], flags: ["-p: create parent directories as needed.", "-v: show each created directory."], examples: [{ title: "Create one directory", code: "mkdir lab", explanation: "Creates a new directory named lab." }, { title: "Create a nested path", code: "mkdir -p notes/linux/ch1", explanation: "Builds all missing directories in the path." }] },
    { command: "cp", summary: "Copy files and directories.", syntax: "cp [options] <source> <destination>", purpose: "Creates a duplicate of a file or directory at another location.", usages: ["Copy a file to a new path.", "Clone an entire directory recursively."], flags: ["-r: recursive copy for directories.", "-i: prompt before overwrite.", "-a: archive mode to preserve metadata."], examples: [{ title: "Copy a file", code: "cp hosts.txt backup/hosts.txt", explanation: "Copies hosts.txt into the backup directory." }, { title: "Copy a directory tree", code: "cp -r project project_copy", explanation: "Duplicates a full directory and everything inside it." }] },
    { command: "mv", summary: "Move or rename files and directories.", syntax: "mv [options] <source> <destination>", purpose: "Relocates files or directories, or renames them in place.", usages: ["Rename a file.", "Move a file into another directory."], flags: ["-i: ask before overwrite.", "-n: do not overwrite existing files.", "-v: show each move."], examples: [{ title: "Rename a file", code: "mv oldname.txt newname.txt", explanation: "Changes the file name in place." }, { title: "Move a file", code: "mv report.txt /tmp/", explanation: "Moves report.txt into /tmp." }] },
    { command: "rm", summary: "Remove files and directories.", syntax: "rm [options] <target>", purpose: "Deletes files and can remove directory trees recursively.", usages: ["Delete unwanted files.", "Remove directories with caution using recursion."], flags: ["-r: recursive removal.", "-f: force deletion.", "-i: prompt before removing each file."], examples: [{ title: "Remove a file", code: "rm sample.txt", explanation: "Deletes sample.txt permanently." }, { title: "Remove a directory tree", code: "rm -r old_logs", explanation: "Deletes the directory and all content beneath it." }] },
    { command: "rmdir", summary: "Remove empty directories.", syntax: "rmdir <directory>", purpose: "Deletes directories only if they are empty.", usages: ["Remove empty folders safely.", "Useful when you want directory-only deletion without recursive file removal."], flags: ["-p: remove parent directories as they become empty."], examples: [{ title: "Remove an empty folder", code: "rmdir emptydir", explanation: "Deletes the directory if it has no contents." }, { title: "Remove nested empty folders", code: "rmdir -p notes/linux/ch1", explanation: "Removes the leaf folder and any newly empty parents." }] }
  ]},
  { unit: "Chapter 2: Text Manipulation", items: [
    { command: "cat", summary: "Display file contents.", syntax: "cat [options] <file>", purpose: "Prints file contents to standard output and can concatenate multiple files.", usages: ["Quickly read a short file.", "Join multiple files into one output stream."], flags: ["-n: number all output lines.", "-b: number only non-blank lines.", "-A: show tabs and line endings."], examples: [{ title: "Show a file", code: "cat notes.txt", explanation: "Prints the contents of notes.txt." }, { title: "Show numbered lines", code: "cat -n notes.txt", explanation: "Displays line numbers next to each line." }] },
    { command: "head", summary: "Show the beginning of a file.", syntax: "head [options] <file>", purpose: "Prints the first lines or bytes from a file or stream.", usages: ["Preview the start of a large file.", "Check file headers or the first log entries."], flags: ["-n <number>: number of lines to show.", "-c <bytes>: show a number of bytes instead of lines."], examples: [{ title: "Show the first ten lines", code: "head access.log", explanation: "Displays the first ten lines by default." }, { title: "Show the first five lines", code: "head -n 5 passwd.txt", explanation: "Prints only the first five lines." }] },
    { command: "tail", summary: "Show the end of a file.", syntax: "tail [options] <file>", purpose: "Prints the final lines or bytes from a file and can follow live updates.", usages: ["Read the latest log entries.", "Watch a log file as new lines are appended."], flags: ["-n <number>: number of lines to show.", "-f: follow output in real time."], examples: [{ title: "Show recent log entries", code: "tail -n 20 /var/log/auth.log", explanation: "Prints the last 20 lines of the log." }, { title: "Follow a log", code: "tail -f /var/log/syslog", explanation: "Keeps printing new lines as the file grows." }] },
    { command: "nl", summary: "Number the lines of a file.", syntax: "nl [options] <file>", purpose: "Prints file content with line numbers, which is useful for review and debugging.", usages: ["Add line numbers to notes or scripts.", "Reference exact line positions in text output."], flags: ["-b a: number all lines.", "-v <n>: start numbering at a chosen value."], examples: [{ title: "Number a file", code: "nl notes.txt", explanation: "Displays notes.txt with line numbers." }, { title: "Number all lines", code: "nl -b a notes.txt", explanation: "Numbers blank lines as well as text lines." }] },
    { command: "grep", summary: "Search text using patterns.", syntax: "grep [options] <pattern> <file>", purpose: "Finds lines that match a word or regular expression in files or command output.", usages: ["Search logs for suspicious terms.", "Filter the output of another command in a pipeline."], flags: ["-i: ignore case.", "-n: show line numbers.", "-r: recursive search.", "-v: invert the match."], examples: [{ title: "Search a file", code: "grep root /etc/passwd", explanation: "Prints lines containing root." }, { title: "Recursive case-insensitive search", code: "grep -rin password .", explanation: "Searches the current directory tree for password in any case." }] },
    { command: "sed", summary: "Stream editor for finding and replacing text.", syntax: "sed [options] 'expression' <file>", purpose: "Transforms text streams and files, often used for substitution or line editing.", usages: ["Replace one word with another.", "Print or modify selected lines in a stream."], flags: ["-n: suppress automatic printing.", "-i: edit files in place.", "s/old/new/g: substitute text globally."], examples: [{ title: "Replace one word with another", code: "sed 's/root/admin/g' users.txt", explanation: "Replaces every root match with admin in the output." }, { title: "Edit a file in place", code: "sed -i 's/oldip/newip/g' config.txt", explanation: "Changes matching text directly inside config.txt." }] },
    { command: "more", summary: "View text one screen at a time.", syntax: "more <file>", purpose: "Lets you read longer files page by page in a simple pager.", usages: ["Read long files without flooding the terminal.", "Step through file output page by page."], flags: ["Space: move to the next page.", "q: quit the pager."], examples: [{ title: "Page through a file", code: "more /etc/services", explanation: "Opens the file in a simple pager view." }] },
    { command: "less", summary: "Open a scrollable pager for text files.", syntax: "less [options] <file>", purpose: "Displays long files interactively with scrolling and search support.", usages: ["Inspect large logs safely.", "Search within a file using /pattern."], flags: ["-N: show line numbers.", "-S: disable line wrapping.", "+G: open at the end of the file."], examples: [{ title: "Open a file in less", code: "less /var/log/syslog", explanation: "Lets you scroll through a large log file." }, { title: "Open with line numbers", code: "less -N notes.txt", explanation: "Shows line numbers while you read." }] }
  ]},
  { unit: "Chapter 3: Analyzing and Managing Networks", items: [
    { command: "ifconfig", summary: "Inspect or configure network interfaces.", syntax: "ifconfig [interface] [options]", purpose: "Legacy network command used to view and change interface settings.", usages: ["Check interface addresses and status.", "Bring interfaces up or down on older setups."], flags: ["up: enable the interface.", "down: disable the interface.", "netmask <mask>: set the network mask."], examples: [{ title: "Show interfaces", code: "ifconfig", explanation: "Displays interface configuration details." }, { title: "Set an address", code: "sudo ifconfig eth0 192.168.1.115 netmask 255.255.255.0", explanation: "Assigns a new IP address and network mask to eth0." }] },
    { command: "netstat", summary: "Display network connections and routes.", syntax: "netstat [options]", purpose: "Shows network connections, listening ports, interface statistics, and routing data on systems with net-tools.", usages: ["See which ports are listening.", "Inspect active network connections."], flags: ["-tuln: show listening TCP and UDP ports numerically.", "-r: display the routing table.", "-i: show interface statistics."], examples: [{ title: "List listening ports", code: "netstat -tuln", explanation: "Displays listening TCP and UDP sockets." }, { title: "Show routes", code: "netstat -r", explanation: "Prints the routing table." }] },
    { command: "ss", summary: "Show socket statistics.", syntax: "ss [options]", purpose: "Modern replacement for many netstat tasks, especially connection and port inspection.", usages: ["Inspect TCP or UDP listening sockets.", "Check which process owns a socket."], flags: ["-t: TCP sockets.", "-u: UDP sockets.", "-l: listening sockets.", "-p: show process names."], examples: [{ title: "Show listening TCP ports", code: "ss -tl", explanation: "Lists TCP sockets waiting for connections." }, { title: "Show ports with processes", code: "sudo ss -tulpn", explanation: "Shows listening sockets and the process using each one." }] },
    { command: "iwconfig", summary: "Inspect wireless interface settings.", syntax: "iwconfig [interface]", purpose: "Legacy wireless tool used to view Wi-Fi-related interface details.", usages: ["Check whether a wireless adapter is present.", "View SSID, mode, and signal information."], flags: ["essid <name>: set the wireless network name.", "mode managed|monitor: set interface mode."], examples: [{ title: "Display wireless devices", code: "iwconfig", explanation: "Prints information about wireless interfaces." }, { title: "Set a wireless network name", code: "sudo iwconfig wlan0 essid TestNetwork", explanation: "Configures wlan0 to use the named ESSID." }] },
    { command: "ip", summary: "Modern network interface and route management tool.", syntax: "ip [object] [command]", purpose: "Shows and manages addresses, links, routes, and neighbors on Linux.", usages: ["Inspect addresses and routing tables.", "Replace several legacy ifconfig or route use cases."], flags: ["addr: show or manage IP addresses.", "link: show or manage interfaces.", "route: show or manage routes."], examples: [{ title: "Show all addresses", code: "ip addr show", explanation: "Lists interfaces and their assigned addresses." }, { title: "Bring an interface up", code: "sudo ip link set eth0 up", explanation: "Enables the eth0 interface." }] },
    { command: "macchanger", summary: "Change or spoof a network card MAC address.", syntax: "macchanger [options] <interface>", purpose: "Alters the MAC address of a network interface for privacy or testing.", usages: ["Spoof a hardware address before connecting to a network.", "Randomize the MAC on wireless interfaces."], flags: ["-r: random MAC address.", "-m <mac>: set a specific MAC address.", "-s: show current MAC details."], examples: [{ title: "Randomize the MAC", code: "sudo macchanger -r wlan0", explanation: "Assigns a random MAC address to wlan0." }, { title: "Show MAC information", code: "macchanger -s wlan0", explanation: "Displays current and permanent MAC address data." }] },
    { command: "dhclient", summary: "Request an IP address from DHCP.", syntax: "dhclient [interface]", purpose: "Asks a DHCP server to assign network configuration to an interface.", usages: ["Obtain a new dynamic IP address.", "Refresh an interface lease after configuration changes."], flags: ["-r: release the current lease.", "-v: verbose output."], examples: [{ title: "Request a new address", code: "sudo dhclient eth0", explanation: "Requests DHCP configuration for eth0." }, { title: "Release the current lease", code: "sudo dhclient -r eth0", explanation: "Releases the DHCP lease assigned to eth0." }] },
    { command: "dig", summary: "Query DNS servers for records.", syntax: "dig [name] [type]", purpose: "Examines DNS information and can query specific records from DNS servers.", usages: ["Check how a domain resolves.", "Troubleshoot DNS configuration and responses."], flags: ["@<server>: query a specific DNS server.", "+short: show brief output.", "<type>: request a record type such as A, MX, or TXT."], examples: [{ title: "Query an A record", code: "dig example.com", explanation: "Requests DNS records for example.com." }, { title: "Use a specific resolver", code: "dig @8.8.8.8 example.com +short", explanation: "Queries Google's resolver and prints a brief answer." }] },
    { command: "host", summary: "Simple DNS lookup utility.", syntax: "host <name> [server]", purpose: "Performs quick DNS lookups for hostnames and IP addresses.", usages: ["Resolve domain names to IP addresses.", "Check reverse lookups on IP addresses."], flags: ["-t <type>: specify a record type such as MX or TXT."], examples: [{ title: "Resolve a hostname", code: "host openai.com", explanation: "Looks up DNS records for the domain." }, { title: "Check MX records", code: "host -t mx example.com", explanation: "Requests the mail exchanger records for the domain." }] }
  ]},
  { unit: "Chapter 4: Adding and Removing Software", items: [
    { command: "apt", summary: "Install, remove, and update packages on Debian-based systems.", syntax: "apt <action> [package]", purpose: "Handles package management tasks such as search, install, remove, update, and upgrade.", usages: ["Install new software from repositories.", "Refresh and upgrade package metadata and packages."], flags: ["update: refresh package lists.", "install: install a package.", "remove: uninstall a package.", "upgrade: upgrade installed packages."], examples: [{ title: "Refresh package lists", code: "sudo apt update", explanation: "Downloads current package metadata from configured repositories." }, { title: "Install a package", code: "sudo apt install wireshark", explanation: "Installs wireshark and its required dependencies." }] },
    { command: "apt-cache", summary: "Query package metadata and package search results.", syntax: "apt-cache <action> [pattern]", purpose: "Lets you inspect package names, versions, and descriptions in the local package cache.", usages: ["Search for packages by keyword.", "View package metadata before installing."], flags: ["search <term>: search package names and descriptions.", "show <package>: display detailed package information."], examples: [{ title: "Search packages", code: "apt-cache search proxy", explanation: "Lists packages whose names or descriptions match proxy." }, { title: "Show details", code: "apt-cache show tor", explanation: "Displays the package metadata for tor." }] },
    { command: "dpkg", summary: "Low-level Debian package tool.", syntax: "dpkg [options] <package-file>", purpose: "Installs, removes, and queries local Debian package files.", usages: ["Install a local .deb file.", "List installed packages on the system."], flags: ["-i <file.deb>: install a package file.", "-l: list installed packages.", "-r <package>: remove a package."], examples: [{ title: "Install a local package", code: "sudo dpkg -i package.deb", explanation: "Installs the Debian package file manually." }, { title: "List installed packages", code: "dpkg -l", explanation: "Shows installed packages known to dpkg." }] },
    { command: "git", summary: "Clone and manage source code repositories.", syntax: "git <action> [arguments]", purpose: "Distributed version control tool commonly used to download and update source code from repositories.", usages: ["Clone security tools from GitHub or other hosts.", "Pull upstream changes into a local repository."], flags: ["clone <url>: copy a remote repository.", "pull: fetch and integrate changes.", "status: show working tree state."], examples: [{ title: "Clone a repository", code: "git clone https://github.com/example/tool.git", explanation: "Downloads a copy of the remote repository." }, { title: "Update a repository", code: "git pull", explanation: "Fetches and merges the latest changes." }] }
  ]},
  { unit: "Chapter 5: Controlling File and Directory Permissions", items: [
    { command: "id", summary: "Show user and group identity information.", syntax: "id [user]", purpose: "Displays UID, GID, and group membership for a user account.", usages: ["Inspect the identity and groups of the current user.", "Check group membership before changing permissions."], flags: ["-u: show only the user ID.", "-g: show only the group ID.", "-n: show names instead of numeric IDs."], examples: [{ title: "Show your identity", code: "id", explanation: "Displays UID, GID, and group memberships." }, { title: "Show only the user ID", code: "id -u", explanation: "Prints the numeric user ID." }] },
    { command: "groups", summary: "List group memberships for a user.", syntax: "groups [user]", purpose: "Shows which groups a user belongs to, which affects file access and permissions.", usages: ["Verify whether a user belongs to sudo or shared project groups.", "Check effective group-based access."], flags: ["Basic use typically does not require flags."], examples: [{ title: "Show current group memberships", code: "groups", explanation: "Prints the groups for the current user." }, { title: "Show another user's groups", code: "groups kali", explanation: "Displays the groups the kali user belongs to." }] },
    { command: "chmod", summary: "Change file and directory permissions.", syntax: "chmod [options] <mode> <file>", purpose: "Alters read, write, and execute permissions for users, groups, and others.", usages: ["Make scripts executable.", "Assign numeric permission sets such as 755 or 644."], flags: ["-R: change recursively.", "u g o a: choose permission targets.", "+ - =: add, remove, or set permissions."], examples: [{ title: "Make a script executable", code: "chmod +x script.sh", explanation: "Adds execute permission to the script." }, { title: "Set numeric file permissions", code: "chmod 644 notes.txt", explanation: "Gives the owner read/write and everyone else read-only access." }] },
    { command: "chown", summary: "Change file owner and group.", syntax: "chown [options] <owner>[:group] <file>", purpose: "Transfers ownership of files and directories to another user or group.", usages: ["Fix ownership after root-created files.", "Assign a group owner for shared directories."], flags: ["-R: change recursively.", "owner:group: set both owner and group together."], examples: [{ title: "Change owner", code: "sudo chown kali notes.txt", explanation: "Makes kali the owner of notes.txt." }, { title: "Change owner and group recursively", code: "sudo chown -R kali:kali project", explanation: "Updates the entire project tree." }] },
    { command: "chgrp", summary: "Change a file's group ownership.", syntax: "chgrp [options] <group> <file>", purpose: "Assigns a new group owner to a file or directory without changing the user owner.", usages: ["Share files with a team group.", "Update group access on a directory tree."], flags: ["-R: change group ownership recursively."], examples: [{ title: "Change a file's group", code: "sudo chgrp analysts report.txt", explanation: "Sets analysts as the group owner of report.txt." }, { title: "Change group recursively", code: "sudo chgrp -R www-data /var/www/html", explanation: "Applies the new group to a web root tree." }] },
    { command: "umask", summary: "Set the default permission mask.", syntax: "umask [mode]", purpose: "Controls which permission bits are removed by default when new files and directories are created.", usages: ["Inspect current default creation permissions.", "Harden defaults so new files are private."], flags: ["No argument: display current mask.", "022: common default mask.", "077: owner-only access by default."], examples: [{ title: "Show current mask", code: "umask", explanation: "Prints the shell's active permission mask." }, { title: "Restrict new files heavily", code: "umask 077", explanation: "Removes all group and other permissions by default." }] },
    { command: "sudo", summary: "Run commands with elevated privileges.", syntax: "sudo <command>", purpose: "Executes a command as root or another allowed user when permissions require elevation.", usages: ["Perform administrative package or service operations.", "Modify protected files and system settings."], flags: ["-l: list allowed sudo privileges.", "-u <user>: run the command as another user.", "-k: invalidate cached credentials."], examples: [{ title: "Run an administrative command", code: "sudo apt update", explanation: "Runs apt update with elevated privileges." }, { title: "Run as another account", code: "sudo -u postgres psql", explanation: "Starts psql as the postgres user." }] }
  ]},
  { unit: "Chapter 6: Process Management", items: [
    { command: "ps", summary: "Display running processes.", syntax: "ps [options]", purpose: "Lists processes currently running on the system.", usages: ["Inspect your running commands.", "Find a target process before sending a signal."], flags: ["aux: show all processes in BSD style.", "-ef: show full process list in System V style."], examples: [{ title: "Show all processes", code: "ps aux", explanation: "Prints a detailed list of running processes." }, { title: "Find a process", code: "ps aux | grep apache2", explanation: "Filters the process list for apache2 entries." }] },
    { command: "top", summary: "Monitor processes in real time.", syntax: "top", purpose: "Shows a live-updating process table with CPU, memory, and system load data.", usages: ["Watch which processes use the most CPU or memory.", "Troubleshoot a busy or unresponsive system."], flags: ["P: sort by CPU in the interactive interface.", "M: sort by memory in the interactive interface.", "q: quit the program."], examples: [{ title: "Open top", code: "top", explanation: "Starts a live process and resource monitor." }] },
    { command: "nice", summary: "Start a process with a chosen priority.", syntax: "nice [options] <command>", purpose: "Launches a command with a modified niceness value that influences scheduling priority.", usages: ["Lower priority for heavy background tasks.", "Be more polite to other users on a shared system."], flags: ["-n <value>: set the niceness adjustment."], examples: [{ title: "Start a lower-priority backup", code: "nice -n 10 tar -czf backup.tar.gz project/", explanation: "Runs the backup with reduced scheduling priority." }] },
    { command: "renice", summary: "Change the priority of a running process.", syntax: "renice <priority> -p <pid>", purpose: "Adjusts the niceness value of a process that is already running.", usages: ["Reduce priority of a CPU-heavy task.", "Tune a running process without restarting it."], flags: ["-p <pid>: target a process ID.", "-u <user>: target processes owned by a user."], examples: [{ title: "Lower a running process priority", code: "sudo renice 15 -p 2451", explanation: "Makes process 2451 run with a lower priority." }] },
    { command: "kill", summary: "Send a signal to a process.", syntax: "kill [signal] <pid>", purpose: "Stops or controls a process by sending signals such as TERM or KILL.", usages: ["Terminate a misbehaving program gracefully.", "Force-stop a stuck process when needed."], flags: ["-15: SIGTERM for graceful termination.", "-9: SIGKILL for immediate termination."], examples: [{ title: "Terminate a process", code: "kill 2451", explanation: "Sends the default termination signal to PID 2451." }, { title: "Force-kill a stuck process", code: "kill -9 2451", explanation: "Immediately kills the process." }] },
    { command: "killall", summary: "Send a signal to processes by name.", syntax: "killall [options] <name>", purpose: "Targets all running processes that match a process name.", usages: ["Stop every instance of a process quickly.", "Useful when you know the name but not the PID."], flags: ["-9: send SIGKILL.", "-u <user>: restrict matches to a specific user."], examples: [{ title: "Stop all Firefox processes", code: "killall firefox", explanation: "Terminates running firefox processes." }, { title: "Force-stop a service process name", code: "sudo killall -9 apache2", explanation: "Sends SIGKILL to all apache2 processes." }] },
    { command: "bg", summary: "Resume a stopped job in the background.", syntax: "bg [%job]", purpose: "Takes a suspended shell job and lets it continue running in the background.", usages: ["Keep a job running while you continue using the shell.", "Combine with jobs and fg for job control."], flags: ["%job: specify the shell job number."], examples: [{ title: "Resume the most recent job", code: "bg", explanation: "Continues the most recently stopped job in the background." }] },
    { command: "fg", summary: "Bring a background job to the foreground.", syntax: "fg [%job]", purpose: "Moves a background or stopped shell job into the foreground.", usages: ["Interact with a job that was sent to the background.", "Resume a suspended program in the terminal."], flags: ["%job: specify the shell job number."], examples: [{ title: "Bring a job to the foreground", code: "fg %1", explanation: "Moves job 1 into the foreground." }] },
    { command: "jobs", summary: "List jobs started from the current shell.", syntax: "jobs", purpose: "Shows backgrounded or suspended jobs managed by the current shell.", usages: ["Check which jobs are stopped or running in the background.", "Identify job numbers for bg and fg."], flags: ["-l: show process IDs along with job information."], examples: [{ title: "Show shell jobs", code: "jobs -l", explanation: "Displays shell job numbers and related PIDs." }] }
  ]},
  { unit: "Chapter 7: Managing User Environment Variables", items: [
    { command: "env", summary: "Show or run commands with a modified environment.", syntax: "env [options] [command]", purpose: "Displays the current environment or runs a command with temporary environment changes.", usages: ["Inspect the current environment.", "Run a one-off command with custom variables."], flags: ["-i: start with an empty environment."], examples: [{ title: "Show environment variables", code: "env", explanation: "Prints the environment available to the shell." }, { title: "Run with a temporary variable", code: "env DEBUG=1 ./script.sh", explanation: "Runs the script with DEBUG set only for that command." }] },
    { command: "printenv", summary: "Print environment variables.", syntax: "printenv [variable]", purpose: "Displays all environment variables or the value of one specific variable.", usages: ["Check PATH or HOME values.", "Inspect exported environment variables."], flags: ["No argument: show all environment variables."], examples: [{ title: "Show PATH", code: "printenv PATH", explanation: "Prints the current PATH value." }, { title: "Show all exported variables", code: "printenv", explanation: "Lists exported environment variables." }] },
    { command: "export", summary: "Set environment variables for child processes.", syntax: "export <name>=<value>", purpose: "Marks shell variables for export so they become environment variables for child processes.", usages: ["Set PATH additions or temporary variables.", "Share variables with scripts or subprocesses."], flags: ["-p: print exported variables in a reusable format."], examples: [{ title: "Set a variable", code: "export TARGET=192.168.1.10", explanation: "Creates an environment variable named TARGET." }, { title: "Append to PATH", code: "export PATH=$PATH:/opt/tools", explanation: "Adds /opt/tools to the current PATH." }] },
    { command: "echo", summary: "Print text or variable values.", syntax: "echo [text]", purpose: "Outputs text, variable content, or command-friendly strings in the shell.", usages: ["Verify variable values.", "Write simple output inside shell scripts."], flags: ["-e: enable backslash escapes on many shells.", "-n: suppress the trailing newline."], examples: [{ title: "Print a variable", code: "echo $PATH", explanation: "Displays the current PATH variable value." }, { title: "Print text without a newline", code: "echo -n \"scan started\"", explanation: "Prints text on the same line without an ending newline." }] },
    { command: "source", summary: "Read and execute commands from a file in the current shell.", syntax: "source <file>", purpose: "Loads a shell file so variable or alias changes affect the current shell session.", usages: ["Apply changes made to .bashrc immediately.", "Load reusable shell settings or functions."], flags: [". <file>: common shorthand syntax in many shells."], examples: [{ title: "Reload bash configuration", code: "source ~/.bashrc", explanation: "Applies .bashrc changes without opening a new shell." }] },
    { command: "bash", summary: "Start a Bash shell.", syntax: "bash [options] [script]", purpose: "Launches a Bash shell or runs a shell script with Bash.", usages: ["Open a new shell session.", "Run a script explicitly with Bash."], flags: ["-c '<command>': execute a single command string.", "-x: trace commands as they execute.", "-i: start an interactive shell."], examples: [{ title: "Run a script", code: "bash scanner.sh", explanation: "Executes scanner.sh with Bash." }, { title: "Run one command", code: "bash -c 'echo $SHELL'", explanation: "Starts a new Bash instance to run one command string." }] },
    { command: "chsh", summary: "Change the default login shell.", syntax: "chsh [options] <user>", purpose: "Updates which shell starts by default when a user logs in.", usages: ["Switch a user to Bash or another allowed shell.", "Check or modify the login shell setting."], flags: ["-s <shell>: set the new login shell.", "-l: list allowed shells on some systems."], examples: [{ title: "Set Bash as the default shell", code: "chsh -s /bin/bash", explanation: "Changes the current user's default login shell to Bash." }] }
  ]},
  { unit: "Chapter 8: Bash Scripting", items: [
    { command: "read", summary: "Read user input into shell variables.", syntax: "read [options] <name>", purpose: "Accepts input from the keyboard or standard input inside a Bash script.", usages: ["Prompt the user for targets or ports in a script.", "Collect values interactively."], flags: ["-p '<prompt>': show a prompt.", "-s: silent mode for sensitive input.", "-r: read raw input without backslash escapes."], examples: [{ title: "Prompt for a host", code: "read -p \"Host: \" host", explanation: "Stores the entered host value in the host variable." }] },
    { command: "test", summary: "Evaluate conditions in shell scripts.", syntax: "test <expression>", purpose: "Checks conditions such as file existence, string equality, or numeric comparisons.", usages: ["Control if statements in Bash.", "Test whether files exist before acting on them."], flags: ["[ ... ]: common shell synonym for test.", "-f: file exists and is a regular file.", "-d: path exists and is a directory."], examples: [{ title: "Check whether a file exists", code: "test -f targets.txt", explanation: "Returns true if targets.txt exists as a regular file." }, { title: "Use bracket form", code: "[ -d /etc ]", explanation: "Tests whether /etc exists and is a directory." }] },
    { command: "chmod-script", summary: "Script execution setup using chmod.", syntax: "chmod +x <script>", purpose: "Common Bash-scripting step that marks a script as executable so it can be run directly.", usages: ["Prepare a new Bash script for execution.", "Apply execute permission before using ./script.sh."], flags: ["Uses chmod semantics; +x adds execute permission."], examples: [{ title: "Make a script executable", code: "chmod +x scanner.sh", explanation: "Lets you run the script directly with ./scanner.sh." }] }
  ]},
  { unit: "Chapter 9: Compressing and Archiving", items: [
    { command: "tar", summary: "Create, extract, and inspect tar archives.", syntax: "tar [options] <archive> [files]", purpose: "Bundles multiple files into a single archive and can work with compression options.", usages: ["Create a backup archive.", "Extract bundled files."], flags: ["-c: create an archive.", "-x: extract an archive.", "-t: list contents.", "-v: verbose mode.", "-f <file>: specify archive file."], examples: [{ title: "Create an archive", code: "tar -cvf backup.tar project/", explanation: "Creates a tar archive from the project directory." }, { title: "Extract an archive", code: "tar -xvf backup.tar", explanation: "Extracts the files stored in backup.tar." }] },
    { command: "gzip", summary: "Compress files with gzip.", syntax: "gzip [options] <file>", purpose: "Compresses files into .gz format using the gzip algorithm.", usages: ["Shrink log files or archives.", "Prepare compressed files for transport or storage."], flags: ["-d: decompress.", "-k: keep the original file.", "-r: process directories recursively on some systems."], examples: [{ title: "Compress a file", code: "gzip wordlist.txt", explanation: "Replaces wordlist.txt with the compressed wordlist.txt.gz." }, { title: "Keep the original file", code: "gzip -k report.txt", explanation: "Creates report.txt.gz without deleting report.txt." }] },
    { command: "gunzip", summary: "Decompress gzip-compressed files.", syntax: "gunzip <file.gz>", purpose: "Expands .gz files back into their original form.", usages: ["Restore compressed text or backup files.", "Reverse a previous gzip operation."], flags: ["-k: keep the compressed file while decompressing."], examples: [{ title: "Decompress a file", code: "gunzip backup.sql.gz", explanation: "Restores backup.sql from backup.sql.gz." }] },
    { command: "bzip2", summary: "Compress files with bzip2.", syntax: "bzip2 [options] <file>", purpose: "Compresses files using the bzip2 algorithm, often yielding better compression than gzip.", usages: ["Compress files when size matters more than speed.", "Create .bz2 versions of large files."], flags: ["-d: decompress.", "-k: keep original file."], examples: [{ title: "Compress a file", code: "bzip2 image.raw", explanation: "Creates image.raw.bz2 and usually removes the original." }] },
    { command: "bunzip2", summary: "Decompress bzip2 files.", syntax: "bunzip2 <file.bz2>", purpose: "Restores files compressed with bzip2.", usages: ["Expand .bz2 data back to its original file.", "Reverse a bzip2 compression step."], flags: ["-k: keep the compressed file."], examples: [{ title: "Decompress a file", code: "bunzip2 image.raw.bz2", explanation: "Restores image.raw from its bzip2-compressed form." }] },
    { command: "compress", summary: "Compress files with the classic UNIX compress utility.", syntax: "compress [options] <file>", purpose: "Legacy compression command that creates .Z files on systems where it is available.", usages: ["Work with older UNIX-style compressed files.", "Use in compatibility scenarios."], flags: ["-v: verbose output.", "-f: force overwrite."], examples: [{ title: "Compress a file", code: "compress olddump.txt", explanation: "Creates olddump.txt.Z using the compress utility." }] },
    { command: "uncompress", summary: "Decompress .Z files.", syntax: "uncompress <file.Z>", purpose: "Reverses the classic UNIX compress format.", usages: ["Restore legacy .Z archives.", "Expand old UNIX-compressed files."], flags: ["-v: verbose output."], examples: [{ title: "Decompress a .Z file", code: "uncompress olddump.txt.Z", explanation: "Restores the original olddump.txt file." }] },
    { command: "dd", summary: "Copy data block by block.", syntax: "dd if=<input> of=<output> [options]", purpose: "Performs low-level data copying, often used for disk imaging and forensic duplication.", usages: ["Create bit-for-bit copies of drives.", "Write image files to storage devices with care."], flags: ["if=: input file or device.", "of=: output file or device.", "bs=: block size.", "status=progress: show progress updates."], examples: [{ title: "Create a disk image", code: "sudo dd if=/dev/sdb of=usb-image.img bs=4M status=progress", explanation: "Copies the source device to a raw image file." }, { title: "Write an image to a device", code: "sudo dd if=kali.iso of=/dev/sdb bs=4M status=progress", explanation: "Writes an ISO image directly to a target device." }] }
  ]},
  { unit: "Chapter 10: Filesystem and Storage Device Management", items: [
    { command: "lsblk", summary: "List block devices.", syntax: "lsblk [options]", purpose: "Displays disks, partitions, and mount points in a tree-like layout.", usages: ["Identify disks and partitions.", "Confirm device names before mounting or imaging."], flags: ["-f: show filesystem information.", "-o <cols>: choose displayed columns."], examples: [{ title: "Show storage devices", code: "lsblk", explanation: "Lists block devices and their partition layout." }, { title: "Show filesystems", code: "lsblk -f", explanation: "Adds filesystem type and label details." }] },
    { command: "lsusb", summary: "List USB devices.", syntax: "lsusb", purpose: "Displays connected USB devices and basic identifying information.", usages: ["Verify that a USB adapter is detected.", "Identify wireless or storage devices connected over USB."], flags: ["-v: verbose information."], examples: [{ title: "Show USB devices", code: "lsusb", explanation: "Prints connected USB devices and vendor/product IDs." }] },
    { command: "mount", summary: "Attach a filesystem to the directory tree.", syntax: "mount [options] <device> <mountpoint>", purpose: "Makes a filesystem available under a mount point in the Linux directory tree.", usages: ["Mount a disk, partition, or USB drive.", "Review currently mounted filesystems."], flags: ["-t <type>: specify filesystem type.", "-o <options>: set mount options."], examples: [{ title: "Mount a USB partition", code: "sudo mount /dev/sdb1 /mnt/usb", explanation: "Attaches /dev/sdb1 at /mnt/usb." }, { title: "List mounted filesystems", code: "mount", explanation: "Prints currently mounted filesystems." }] },
    { command: "umount", summary: "Unmount a filesystem.", syntax: "umount <mountpoint|device>", purpose: "Detaches a mounted filesystem from the directory tree safely.", usages: ["Unmount removable media before unplugging it.", "Release a mounted filesystem after use."], flags: ["-l: lazy unmount.", "-f: force unmount on some systems."], examples: [{ title: "Unmount by mount point", code: "sudo umount /mnt/usb", explanation: "Safely detaches the filesystem mounted at /mnt/usb." }] },
    { command: "df", summary: "Report filesystem disk space usage.", syntax: "df [options] [path]", purpose: "Shows total, used, and available space on mounted filesystems.", usages: ["Check free disk space.", "Confirm whether a filesystem is nearly full."], flags: ["-h: human-readable sizes.", "-T: show filesystem type."], examples: [{ title: "Show disk usage", code: "df -h", explanation: "Displays mounted filesystems with readable sizes." }] },
    { command: "du", summary: "Estimate file and directory disk usage.", syntax: "du [options] <path>", purpose: "Measures how much space files and directories consume.", usages: ["Find large directories.", "Inspect storage usage inside a project tree."], flags: ["-h: human-readable sizes.", "-s: summary only.", "--max-depth=<n>: limit recursion depth."], examples: [{ title: "Summarize a directory", code: "du -sh /var/log", explanation: "Shows total disk usage for /var/log." }, { title: "Inspect top-level folders", code: "du -h --max-depth=1 /home", explanation: "Shows size usage one level below /home." }] },
    { command: "fsck", summary: "Check and repair filesystems.", syntax: "fsck [options] <device>", purpose: "Examines a filesystem for errors and can attempt repairs.", usages: ["Check a filesystem after improper shutdown or corruption.", "Run maintenance checks on unmounted filesystems."], flags: ["-y: answer yes to repair prompts.", "-N: show what would be done without running it."], examples: [{ title: "Check a partition", code: "sudo fsck /dev/sdb1", explanation: "Scans the filesystem on /dev/sdb1 for errors." }] }
  ]},
  { unit: "Chapter 11: The Logging System", items: [
    { command: "journalctl", summary: "Query the systemd journal.", syntax: "journalctl [options]", purpose: "Reads and filters system logs stored by the systemd journal.", usages: ["Inspect boot logs and service logs.", "Filter logs by priority, service, or time."], flags: ["-u <service>: show logs for one service.", "-b: show current boot logs.", "-p <level>: filter by priority.", "-f: follow new log entries live."], examples: [{ title: "Show SSH logs", code: "journalctl -u ssh", explanation: "Displays journal entries for the SSH service." }, { title: "Follow current boot logs", code: "journalctl -b -f", explanation: "Shows logs from the current boot and follows new entries." }] },
    { command: "logrotate", summary: "Rotate and manage log files.", syntax: "logrotate [options] <config>", purpose: "Archives, compresses, and rotates log files according to configuration rules.", usages: ["Force a manual log rotation.", "Test log rotation configurations."], flags: ["-f: force rotation.", "-d: debug mode without making changes.", "-v: verbose output."], examples: [{ title: "Force log rotation", code: "sudo logrotate -f /etc/logrotate.conf", explanation: "Runs a forced rotation using the system logrotate configuration." }] },
    { command: "logger", summary: "Write a message to the system log.", syntax: "logger [options] <message>", purpose: "Sends custom messages to syslog or the system journal.", usages: ["Generate test log entries.", "Mark events during scripts or incident response."], flags: ["-p <facility.level>: choose a syslog priority.", "-t <tag>: set a message tag."], examples: [{ title: "Write a test log entry", code: "logger -t audit \"manual log test\"", explanation: "Sends a tagged message to the logging system." }] }
  ]},
  { unit: "Chapter 12: Using and Abusing Services", items: [
    { command: "systemctl", summary: "Manage systemd services.", syntax: "systemctl <action> <service>", purpose: "Starts, stops, restarts, enables, disables, and inspects services on systemd-based systems.", usages: ["Check service health.", "Enable a service to start at boot."], flags: ["status: show service state.", "start|stop|restart: control runtime state.", "enable|disable: control startup behavior."], examples: [{ title: "Check Apache status", code: "sudo systemctl status apache2", explanation: "Shows whether apache2 is active and recent related log lines." }, { title: "Enable SSH on boot", code: "sudo systemctl enable ssh", explanation: "Configures SSH to start automatically at boot." }] },
    { command: "service", summary: "Legacy service management wrapper.", syntax: "service <name> <action>", purpose: "Starts, stops, or restarts services using a SysV-style interface on systems where it is available.", usages: ["Manage services on older systems or with compatibility wrappers.", "Quickly start or stop common services."], flags: ["status: show current state.", "start|stop|restart: control the service."], examples: [{ title: "Restart Apache", code: "sudo service apache2 restart", explanation: "Restarts the apache2 service." }] },
    { command: "apache2ctl", summary: "Control and inspect Apache HTTP server.", syntax: "apache2ctl <action>", purpose: "Provides administrative commands for the Apache web server.", usages: ["Test Apache configuration.", "Start or restart Apache through its control utility."], flags: ["configtest: check configuration syntax.", "graceful: reload configuration gracefully.", "restart: restart the web server."], examples: [{ title: "Test Apache config", code: "sudo apache2ctl configtest", explanation: "Checks Apache configuration files for syntax errors." }] },
    { command: "ssh", summary: "Connect securely to a remote host.", syntax: "ssh [options] <user>@<host>", purpose: "Creates an encrypted remote shell session using the SSH protocol.", usages: ["Log into remote Linux systems.", "Run a command on a remote host securely."], flags: ["-p <port>: choose a non-default SSH port.", "-i <keyfile>: use a specific private key."], examples: [{ title: "Connect to a remote system", code: "ssh kali@192.168.1.20", explanation: "Starts an SSH session to the remote host." }, { title: "Use a private key", code: "ssh -i ~/.ssh/id_rsa user@example.com", explanation: "Authenticates with the specified key file." }] },
    { command: "mysql", summary: "Open the MySQL or MariaDB command-line client.", syntax: "mysql [options] [-u user] [-p] [database]", purpose: "Connects to a MySQL-compatible database server for queries and administration.", usages: ["Log into MySQL or MariaDB.", "Inspect databases and tables from the shell."], flags: ["-u <user>: specify the username.", "-p: prompt for a password.", "-h <host>: connect to a remote server."], examples: [{ title: "Connect locally", code: "mysql -u root -p", explanation: "Prompts for the root password and opens the database client." }, { title: "Connect to a remote server", code: "mysql -h 192.168.1.50 -u analyst -p", explanation: "Connects to the remote database host as analyst." }] },
    { command: "psql", summary: "Open the PostgreSQL command-line client.", syntax: "psql [options] [database]", purpose: "Connects to a PostgreSQL database server for interactive SQL work.", usages: ["Inspect PostgreSQL databases from the terminal.", "Query tables or manage schemas."], flags: ["-U <user>: specify the username.", "-h <host>: connect to a remote server.", "-d <database>: choose the database."], examples: [{ title: "Connect to a database", code: "psql -U postgres -d appdb", explanation: "Starts an interactive PostgreSQL session for appdb." }] }
  ]},
  { unit: "Chapter 13: Becoming Secure and Anonymous", items: [
    { command: "tor", summary: "Run or control the Tor anonymity network client.", syntax: "tor [options]", purpose: "Starts the Tor service or tests Tor-related configuration depending on how it is installed.", usages: ["Route traffic through Tor for anonymity.", "Check or run the local Tor service."], flags: ["-f <config>: use a specific configuration file.", "--verify-config: verify configuration and exit."], examples: [{ title: "Start Tor with a config file", code: "tor -f /etc/tor/torrc", explanation: "Starts Tor using the specified configuration." }] },
    { command: "proxychains", summary: "Route a command through configured proxy servers.", syntax: "proxychains <command>", purpose: "Runs another command through the proxies defined in the proxychains configuration file.", usages: ["Force a tool to use SOCKS or HTTP proxies.", "Chain applications through Tor or multiple proxies."], flags: ["-f <file>: use an alternate configuration file.", "-q: quiet mode."], examples: [{ title: "Run Nmap through a proxy chain", code: "proxychains nmap -sT example.com", explanation: "Starts Nmap through the configured proxy chain." }] },
    { command: "openvpn", summary: "Connect to a VPN using an OpenVPN configuration.", syntax: "openvpn --config <file.ovpn>", purpose: "Starts an OpenVPN client session using a provided VPN profile.", usages: ["Connect to a VPN before lab or pentest work.", "Use a configuration file from a VPN provider."], flags: ["--config <file>: specify the VPN profile.", "--daemon: run in the background."], examples: [{ title: "Start a VPN tunnel", code: "sudo openvpn --config client.ovpn", explanation: "Connects to the VPN described by client.ovpn." }] },
    { command: "gpg", summary: "Encrypt, decrypt, and sign files or messages.", syntax: "gpg [options] <file>", purpose: "Provides OpenPGP encryption and signing for secure communication and file protection.", usages: ["Encrypt sensitive files.", "Decrypt files received from others."], flags: ["-c: symmetric encryption.", "-d: decrypt.", "--import: import public keys."], examples: [{ title: "Encrypt a file symmetrically", code: "gpg -c secrets.txt", explanation: "Creates an encrypted version protected by a passphrase." }, { title: "Decrypt a file", code: "gpg -d secrets.txt.gpg", explanation: "Prompts for the passphrase and decrypts the file." }] }
  ]},
  { unit: "Chapter 14: Understanding and Inspecting Wireless Networks", items: [
    { command: "airmon-ng", summary: "Manage wireless monitor mode for aircrack-ng workflows.", syntax: "airmon-ng [start|stop] <interface>", purpose: "Enables or disables monitor mode on supported wireless interfaces.", usages: ["Prepare a wireless card for packet capture.", "Stop monitor mode after wireless testing."], flags: ["start <iface>: enable monitor mode.", "stop <iface>: disable monitor mode."], examples: [{ title: "Start monitor mode", code: "sudo airmon-ng start wlan0", explanation: "Creates or enables a monitor-mode interface for wlan0." }] },
    { command: "airodump-ng", summary: "Capture and inspect wireless traffic.", syntax: "airodump-ng [options] <interface>", purpose: "Sniffs nearby Wi-Fi networks and clients and records wireless capture data.", usages: ["Survey nearby access points and channels.", "Capture handshakes for lab analysis."], flags: ["-c <channel>: lock capture to a channel.", "--bssid <mac>: focus on one access point.", "-w <prefix>: write capture files."], examples: [{ title: "Scan nearby access points", code: "sudo airodump-ng wlan0mon", explanation: "Lists wireless networks and clients seen by the monitor interface." }] },
    { command: "aireplay-ng", summary: "Inject or replay wireless frames.", syntax: "aireplay-ng [options] <interface>", purpose: "Performs packet injection and replay operations in aircrack-ng workflows.", usages: ["Generate traffic for testing in authorized labs.", "Perform deauthentication or replay actions in a capture workflow."], flags: ["--deauth <count>: send deauthentication frames.", "-a <bssid>: target access point MAC.", "-c <client>: target client MAC."], examples: [{ title: "Send deauth frames in a lab", code: "sudo aireplay-ng --deauth 10 -a AA:BB:CC:DD:EE:FF wlan0mon", explanation: "Sends ten deauthentication frames to the chosen access point in an authorized test." }] },
    { command: "aircrack-ng", summary: "Analyze captured wireless handshakes and keys.", syntax: "aircrack-ng [options] <capture-file>", purpose: "Processes wireless capture files, commonly for WPA/WEP key analysis in authorized environments.", usages: ["Analyze handshake captures in a lab.", "Use a wordlist against a captured WPA handshake."], flags: ["-w <wordlist>: specify a wordlist.", "-b <bssid>: focus on one target network."], examples: [{ title: "Attempt WPA key recovery in a lab", code: "aircrack-ng -w rockyou.txt -b AA:BB:CC:DD:EE:FF capture.cap", explanation: "Uses a wordlist to test keys against the captured handshake." }] },
    { command: "bluetoothctl", summary: "Interact with Bluetooth devices from the terminal.", syntax: "bluetoothctl", purpose: "Opens an interactive Bluetooth management shell.", usages: ["Scan for nearby Bluetooth devices.", "Pair, trust, and connect to devices."], flags: ["scan on: start discovery.", "devices: list known devices.", "pair <mac>: pair with a device."], examples: [{ title: "Start the Bluetooth shell", code: "bluetoothctl", explanation: "Opens the interactive Bluetooth control interface." }] },
    { command: "hcitool", summary: "Legacy Bluetooth scanning and control utility.", syntax: "hcitool [command] [options]", purpose: "Provides older command-line Bluetooth discovery and control features where available.", usages: ["Scan for discoverable Bluetooth devices.", "Inspect local Bluetooth interfaces on older systems."], flags: ["scan: scan for nearby devices.", "dev: list local Bluetooth devices."], examples: [{ title: "Scan for Bluetooth devices", code: "hcitool scan", explanation: "Searches for nearby discoverable Bluetooth devices." }] },
    { command: "hciconfig", summary: "Legacy Bluetooth interface configuration tool.", syntax: "hciconfig [device] [options]", purpose: "Shows or changes Bluetooth interface settings on systems with the legacy tools installed.", usages: ["Inspect Bluetooth adapter status.", "Bring Bluetooth interfaces up or down."], flags: ["up: enable the interface.", "down: disable the interface."], examples: [{ title: "Show Bluetooth adapters", code: "hciconfig", explanation: "Displays local Bluetooth device information." }] }
  ]},
  { unit: "Chapter 15: Managing the Linux Kernel and Loadable Kernel Modules", items: [
    { command: "uname", summary: "Show kernel and system information.", syntax: "uname [options]", purpose: "Prints details such as the kernel name, release, and machine architecture.", usages: ["Check the running kernel version.", "Confirm system architecture before installing software."], flags: ["-a: show all available system information.", "-r: show kernel release only.", "-m: show machine hardware name."], examples: [{ title: "Show the kernel version", code: "uname -r", explanation: "Prints just the running kernel release." }, { title: "Show all system info", code: "uname -a", explanation: "Displays kernel, host, architecture, and more." }] },
    { command: "sysctl", summary: "View or tune kernel parameters.", syntax: "sysctl [options] [name[=value]]", purpose: "Reads and changes kernel runtime settings exposed through /proc/sys.", usages: ["Inspect networking and kernel security settings.", "Temporarily change kernel parameter values."], flags: ["-a: display all available parameters.", "-w name=value: write a new value."], examples: [{ title: "Show IP forwarding", code: "sysctl net.ipv4.ip_forward", explanation: "Displays the current IPv4 forwarding setting." }, { title: "Enable IP forwarding temporarily", code: "sudo sysctl -w net.ipv4.ip_forward=1", explanation: "Changes the kernel value until reboot or configuration reload." }] },
    { command: "lsmod", summary: "List loaded kernel modules.", syntax: "lsmod", purpose: "Displays currently loaded kernel modules and their usage counts.", usages: ["Inspect which modules are active.", "Check whether a driver module loaded successfully."], flags: ["Basic use does not usually require flags."], examples: [{ title: "Show loaded modules", code: "lsmod", explanation: "Prints the kernel module table." }] },
    { command: "modinfo", summary: "Show information about a kernel module.", syntax: "modinfo <module>", purpose: "Displays metadata such as version, author, description, and parameters for a module.", usages: ["Inspect a module before loading it.", "Review available options for a device driver."], flags: ["-p: show module parameters.", "-F <field>: print a specific metadata field."], examples: [{ title: "Inspect a module", code: "modinfo iwlwifi", explanation: "Shows metadata about the iwlwifi kernel module." }] },
    { command: "modprobe", summary: "Load or remove kernel modules with dependency handling.", syntax: "modprobe [options] <module>", purpose: "Adds or removes kernel modules while automatically handling dependencies.", usages: ["Load a driver module.", "Unload a module cleanly."], flags: ["-r: remove a module.", "-v: verbose output."], examples: [{ title: "Load a module", code: "sudo modprobe vboxdrv", explanation: "Loads the vboxdrv module and any needed dependencies." }, { title: "Remove a module", code: "sudo modprobe -r vboxdrv", explanation: "Unloads the module cleanly." }] },
    { command: "insmod", summary: "Insert a kernel module directly.", syntax: "insmod <module.ko>", purpose: "Loads a kernel module file directly without automatic dependency resolution.", usages: ["Insert a specific module file manually.", "Useful in low-level troubleshooting."], flags: ["Parameters can follow the module path as key=value pairs."], examples: [{ title: "Insert a module file", code: "sudo insmod custom_module.ko", explanation: "Loads the specified kernel object directly." }] },
    { command: "rmmod", summary: "Remove a loaded kernel module.", syntax: "rmmod <module>", purpose: "Unloads a kernel module by name.", usages: ["Remove a driver or test module from the kernel.", "Reverse a previous insmod or modprobe load."], flags: ["-f: force removal on some systems."], examples: [{ title: "Remove a module", code: "sudo rmmod custom_module", explanation: "Unloads the named module from the running kernel." }] }
  ]},
  { unit: "Chapter 16: Automating Tasks with Job Scheduling", items: [
    { command: "crontab", summary: "Manage scheduled cron jobs.", syntax: "crontab [options]", purpose: "Creates, edits, lists, and removes per-user cron schedules.", usages: ["Schedule recurring scans, backups, or maintenance tasks.", "Inspect the current cron schedule."], flags: ["-e: edit the current crontab.", "-l: list current cron entries.", "-r: remove the current crontab."], examples: [{ title: "Edit cron jobs", code: "crontab -e", explanation: "Opens the current user's cron table for editing." }, { title: "List scheduled jobs", code: "crontab -l", explanation: "Prints the current user's cron schedule." }] },
    { command: "at", summary: "Schedule a one-time job.", syntax: "at <time>", purpose: "Queues a command or script to run once at a specified future time.", usages: ["Delay a one-time backup or scan.", "Schedule tasks that should not repeat."], flags: ["atq: list pending at jobs.", "atrm <job>: remove a queued at job."], examples: [{ title: "Schedule a job for 2 PM", code: "at 2:00 PM", explanation: "Opens a prompt where you type the commands to run at 2 PM." }] },
    { command: "runlevel", summary: "Show the current and previous runlevel.", syntax: "runlevel", purpose: "Reports the current and previous system runlevel on systems where runlevels are still meaningful.", usages: ["Inspect the boot state on SysV-style systems.", "Understand startup behavior in older Linux setups."], flags: ["Basic use does not usually require flags."], examples: [{ title: "Show runlevel", code: "runlevel", explanation: "Prints the previous and current runlevel." }] },
    { command: "update-rc.d", summary: "Manage SysV startup links on Debian-based systems.", syntax: "update-rc.d <service> <action>", purpose: "Adds or removes service startup links for boot-time execution on SysV-compatible systems.", usages: ["Enable a service at startup on older systems.", "Remove startup links for a service."], flags: ["defaults: install default start/stop links.", "remove: delete the startup links."], examples: [{ title: "Add default startup links", code: "sudo update-rc.d apache2 defaults", explanation: "Registers apache2 for standard SysV startup." }] }
  ]},
  { unit: "Chapter 17: Basic Python Scripting for Hackers", items: [
    { command: "python3", summary: "Run the Python 3 interpreter or execute a Python script.", syntax: "python3 [options] [script.py]", purpose: "Launches the Python interpreter for interactive use or runs Python-based automation scripts.", usages: ["Run quick Python commands interactively.", "Execute automation or networking scripts from the terminal."], flags: ["-c '<code>': run a short Python statement.", "-m <module>: run a library module as a script.", "-V: show the Python version."], examples: [{ title: "Open the interpreter", code: "python3", explanation: "Starts an interactive Python 3 shell." }, { title: "Run a script", code: "python3 scanner.py", explanation: "Executes the Python file scanner.py." }] },
    { command: "pip3", summary: "Install and manage Python 3 packages.", syntax: "pip3 <action> [package]", purpose: "Downloads and manages Python libraries used by scripts and tools.", usages: ["Install Python dependencies for hacking scripts.", "Upgrade or remove Python packages."], flags: ["install <package>: install a package.", "list: show installed packages.", "uninstall <package>: remove a package."], examples: [{ title: "Install a package", code: "pip3 install requests", explanation: "Installs the requests library for Python 3." }, { title: "List installed packages", code: "pip3 list", explanation: "Shows currently installed Python packages." }] },
    { command: "python3-http", summary: "Run Python's built-in simple web server module.", syntax: "python3 -m http.server [port]", purpose: "Starts a lightweight HTTP server from the current directory for quick file serving.", usages: ["Share files quickly on a local network.", "Test downloads or serve proof-of-concept content in a lab."], flags: ["-m http.server: run the built-in HTTP server module.", "Optional port: choose a listening port."], examples: [{ title: "Serve the current directory", code: "python3 -m http.server 8000", explanation: "Starts a simple HTTP server on port 8000." }] }
  ]},
];
